insert into Book (id, isbn, title, publisher) values (0, 9780134529301, 'Working with objects', 'Greenwich : Manning : cop. 1996');
insert into Book (id, isbn, title, publisher) values (1, 9780137955923, 'Distributed and parallel computing', 'Greenwich, CT : Manning, c1998.');
insert into Book (id, isbn, title, publisher) values (2, 9781884777011, 'Visual object-oriented programming', 'Greenwich, CT : Manning, c1995.');
insert into Book (id, isbn, title, publisher) values (3, 9780131723979, 'Visual object-oriented programming', 'Greenwich, CT : Manning, c1995.');
insert into Book (id, isbn, title, publisher) values (4, 9780138412142, 'Power 3D', 'Manning, 1997.');
insert into Book (id, isbn, title, publisher) values (5, 9780132280167, 'Mastering tools, taming daemons', 'Greenwich : Manning, c1995.');
insert into Book (id, isbn, title, publisher) values (6, 9781884777073, 'Mastering tools, taming daemons', 'Greenwich : Manning, c1995.');
insert into Book (id, isbn, title, publisher) values (7, 9780133199550, 'Comprehensive networking glossary and acronym guide', 'Greenwich, CT : Manning, c1995.');
insert into Book (id, isbn, title, publisher) values (8, 9781884777028, 'Comprehensive networking glossary and acronym guide', 'Greenwich, CT : Manning, c1995.');
insert into Book (id, isbn, title, publisher) values (9, 9780134411637, 'Visual programming with prograph CPX', 'Greenwich : Manning, c1995.');
insert into Book (id, isbn, title, publisher) values (10, 9781884777059, 'Visual programming with prograph CPX', 'Greenwich : Manning, c1995.');
insert into Book (id, isbn, title, publisher) values (11, 9781884777288, 'Personal videoconferencing', 'Greenwich, CT Manning c1996');
insert into Book (id, isbn, title, publisher) values (12, 9781930110885, 'Swing', 'Greenwich : Manning, c2003.');
insert into Book (id, isbn, title, publisher) values (13, 9781930110588, 'Java development with Ant', 'Greenwich, Conn. : Manning : c2003.');
insert into Book (id, isbn, title, publisher) values (14, 9781930110960, 'Eclipse in action', 'Greenwich, Conn. : Manning, c2003.');
insert into Book (id, isbn, title, publisher) values (15, 9781930110892, 'Jess in action', 'Greenwich, CT : Manning, c2003.');
insert into Book (id, isbn, title, publisher) values (16, 9781932394207, 'Explorer''s guide to the Semantic Web', 'Greenwich : Manning, c2004.');
insert into Book (id, isbn, title, publisher) values (17, 9781932394900, 'Windows PowerShell in action', 'Greenwich, Conn. : Manning, 2007.');
insert into Book (id, isbn, title, publisher) values (18, 9781932394887, 'Java persistence with Hibernate', 'Greenwich, Conn. : Manning, c2007.');
insert into Book (id, isbn, title, publisher) values (19, 9780132683272, 'Personal videoconferencing', 'Greenwich, CT : Manning, c1996.');
insert into Book (id, isbn, title, publisher) values (20, 9781884777295, 'Building secure and reliable network applications', 'Greenwich : Manning, c1996.');
insert into Book (id, isbn, title, publisher) values (21, 9780137195848, 'Building secure and reliable network applications', 'Greenwich : Manning, c1996.');
insert into Book (id, isbn, title, publisher) values (22, 9781932394924, 'NHibernate in action', 'Greenwich : Manning, c2009.');
insert into Book (id, isbn, title, publisher) values (23, 9781884777127, 'Planning and managing ATM networks', 'Greenwich, Conn. : Manning, c1997.');
insert into Book (id, isbn, title, publisher) values (24, 9781930110458, 'JDK 1. 4 tutorial', 'Greenwich, Conn. : Manning, c2002.');
insert into Book (id, isbn, title, publisher) values (25, 9780138411800, 'Implementing PeopleSoft Financials', 'Greenwich, CT : Manning, c1997.');
insert into Book (id, isbn, title, publisher) values (26, 9781930110311, 'Javascript in Action', 'Manning');
insert into Book (id, isbn, title, publisher) values (27, 9780585470092, 'Eclipse in action', 'Greenwich, Conn. : Manning, c2003.');
insert into Book (id, isbn, title, publisher) values (28, 9780132139847, 'Object-oriented application frameworks', 'Manning, 1995.');
insert into Book (id, isbn, title, publisher) values (29, 9781932394337, 'JUnit recipes', 'Greenwich, CT : Manning, c2005.');
insert into Book (id, isbn, title, publisher) values (30, 9781884777325, 'Client/server over ATM', 'Greenwich, CT : Manning, c1997.');
insert into Book (id, isbn, title, publisher) values (31, 9780137353002, 'Client/server over ATM', 'Greenwich, CT : Manning, c1997.');
insert into Book (id, isbn, title, publisher) values (32, 9780722337141, 'Joan''s genealogy', 'Manning, 2006.');
insert into Book (id, isbn, title, publisher) values (33, 9781844777563, 'The awesome power of Java Beans', 'Manning');
insert into Book (id, isbn, title, publisher) values (34, 9781884777066, 'Object-oriented application frameworks', 'Manning, 1995.');
insert into Book (id, isbn, title, publisher) values (35, 9781884777356, 'Implementing PeopleSoft Financials', 'Greenwich, CT : Manning, c1997.');
insert into Book (id, isbn, title, publisher) values (36, 9781884777622, 'Mastering PowerScript', 'Manning');
insert into Book (id, isbn, title, publisher) values (37, 9781592000401, 'Focus on Solid Geometry', 'Manning');
insert into Book (id, isbn, title, publisher) values (38, 9780884777380, 'Coffeehouse Writings From the Web', 'Manning');
insert into Book (id, isbn, title, publisher) values (39, 9781933988665, 'Algorithms of the intelligent Web', 'Greenwich, CT : Manning, c2009.');
insert into Book (id, isbn, title, publisher) values (40, 9780585470085, 'Bitter EJB', 'Greenwich, Conn. : Manning, c2003.');
insert into Book (id, isbn, title, publisher) values (41, 9780585462783, 'Swing', 'Greenwich : Manning, c2003.');
insert into Book (id, isbn, title, publisher) values (42, 9780470869055, 'Eclipse in action', 'Greenwich, Conn. : Manning, c2003.');
insert into Book (id, isbn, title, publisher) values (43, 9780138582425, 'Mobile agents', 'Greenwich, CT : Manning, c1998.');
insert into Book (id, isbn, title, publisher) values (44, 9781884777363, 'Mobile agents', 'Greenwich, CT : Manning, c1998.');
insert into Book (id, isbn, title, publisher) values (45, 9780138582265, 'Illustrated guide to HTTP', 'Greenwich, CT : Manning, c1997.');
insert into Book (id, isbn, title, publisher) values (46, 9780131271685, 'SNA & TCP/IP enterprise networking', 'Greenwich : Manning, c1998.');
insert into Book (id, isbn, title, publisher) values (47, 9781884777370, 'Illustrated guide to HTTP', 'Greenwich, CT : Manning, c1997.');
insert into Book (id, isbn, title, publisher) values (48, 9780133046014, 'How to deliver client/server applications that work', 'Greenwich : Manning, c1995.');
insert into Book (id, isbn, title, publisher) values (49, 9781884777042, 'How to deliver client/server applications that work', 'Greenwich : Manning, c1995.');
insert into Book (id, isbn, title, publisher) values (50, 9781932394856, 'Test driven', 'Greenwich, CT : Manning, c2008.');
insert into Book (id, isbn, title, publisher) values (51, 9780585470290, 'EJB cookbook', 'Greenwich, Conn. : Manning, c2003.');
insert into Book (id, isbn, title, publisher) values (52, 9781884777103, 'Working with objects', 'Greenwich : Manning : cop. 1996');
insert into Book (id, isbn, title, publisher) values (53, 9781930110137, 'Practical Java Message Service', 'Manning');
insert into Book (id, isbn, title, publisher) values (54, 9781884777424, 'Multiprotocol over ATM', 'Greenwich, CT : Manning, c1998.');
insert into Book (id, isbn, title, publisher) values (55, 9780138892708, 'Multiprotocol over ATM', 'Greenwich, CT : Manning, c1998.');
insert into Book (id, isbn, title, publisher) values (56, 9780585470078, 'Struts in action', 'Greenwich, CT : Manning, c2003.');
insert into Book (id, isbn, title, publisher) values (57, 9780585470306, 'Java development with Ant', 'Greenwich, Conn. : Manning ; c2003.');
insert into Book (id, isbn, title, publisher) values (58, 9781884777226, 'Implementing SAP R/3', 'Greenwich : Manning, c1996.');
insert into Book (id, isbn, title, publisher) values (59, 9780132621717, 'Implementing SAP R/3', 'Greenwich : Manning, c1996.');
insert into Book (id, isbn, title, publisher) values (60, 9781930110953, 'Bitter EJB', 'Greenwich, CT : Manning, c2003.');
insert into Book (id, isbn, title, publisher) values (61, 9781932394610, 'Ajax in Action', 'Manning');
insert into Book (id, isbn, title, publisher) values (62, 9780133046199, 'Designing hard software', 'Greenwich : Manning, c1997.');
insert into Book (id, isbn, title, publisher) values (63, 9781884777219, 'Designing hard software', 'Greenwich : Manning, c1997.');
insert into Book (id, isbn, title, publisher) values (64, 9780132621892, 'Planning and managing ATM networks', 'Greenwich, Conn. : Manning, c1997.');
insert into Book (id, isbn, title, publisher) values (65, 9780138892135, 'Implementing SAP R/3', 'Greenwich : Manning, c1998.');
insert into Book (id, isbn, title, publisher) values (66, 9781932394412, 'Hibernate quickly', 'Greenwich, CT : Manning, c2006.');
insert into Book (id, isbn, title, publisher) values (67, 9781932394597, 'Understanding enterprise SOA', 'Greenwich, Conn. : Manning ; 2005.');
insert into Book (id, isbn, title, publisher) values (68, 9781930110823, 'Extending and embedding Perl', 'Greenwich, Conn. : Manning, c2003.');
insert into Book (id, isbn, title, publisher) values (69, 9781930110069, 'Web development with Apache and Perl', 'Greenwich, CT : Manning, c2002.');
insert into Book (id, isbn, title, publisher) values (70, 9781932394559, 'Eclipse in Action', 'Manning');
insert into Book (id, isbn, title, publisher) values (71, 9780722332542, 'Pop''s past', 'Greenwich, CT; Manning');
insert into Book (id, isbn, title, publisher) values (72, 9784381005984, 'Shogi Problems in Japanese and English', 'Man To Man');
insert into Book (id, isbn, title, publisher) values (73, 9780747259541, 'Hothead', 'Man2Man');
insert into Book (id, isbn, title, publisher) values (74, 9780747260653, 'Rude boys', '; Man2Man');
insert into Book (id, isbn, title, publisher) values (75, 9780747260660, 'Neil', '; Man2Man');
insert into Book (id, isbn, title, publisher) values (76, 9780747259558, 'Big business', '; Man2Man');
insert into Book (id, isbn, title, publisher) values (77, 9780747259718, 'Danny boy', '; Man2Man');
insert into Book (id, isbn, title, publisher) values (78, 9780973029116, 'Donegal poit�n', 'Donegal : Aidan Manning, 2002.');
insert into Book (id, isbn, title, publisher) values (79, 9781884777035, 'PIKS foundation C programmer''s guide', 'Greenwich, CT : Manning Publications, c1995.');
insert into Book (id, isbn, title, publisher) values (80, 9780131723399, 'PIKS foundation C programmer''s guide', 'Greenwich, CT : Manning Publications, c1995.');
insert into Book (id, isbn, title, publisher) values (81, 9780138412067, 'Java network programming', 'Manning Publications, 1997.');
insert into Book (id, isbn, title, publisher) values (82, 9781884777349, 'Java network programming', 'Manning Publications, 1997.');
insert into Book (id, isbn, title, publisher) values (83, 9780949680006, 'More and better lambs', 'Kilmore, Vic. : Agri-man, 1982.');
insert into Book (id, isbn, title, publisher) values (84, 9780646345994, 'A tribe inhabiting earth', 'Bibra Lake, W. A. : R. Manning, 1997.');
insert into Book (id, isbn, title, publisher) values (85, 9781930110502, 'Struts in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (86, 9781930110991, 'JUnit in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (87, 9781932394054, 'XDoclet in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (88, 9781932394153, 'Hibernate in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (89, 9781932394238, 'JUnit Recipes', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (90, 9781930110939, 'AspectJ in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (91, 9781932394122, 'JavaServer Faces in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (92, 9781930110977, 'Code Generation in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (93, 9781930110595, 'SCWCD Exam Study Kit', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (94, 9781884777493, 'Java Network Programming', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (95, 9781932394184, 'Java Reflection in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (96, 9781884777905, '3D User Interfaces With Java 3D', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (97, 9781884777592, 'Practical Software Requirements', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (98, 9781932394221, 'Microsoft Reporting Services in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (99, 9781884777745, 'The Quick Python Book', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (100, 9781884777806, 'Elements of Programming with Perl', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (101, 9789176435243, 'Vatten melonen', 'ManPocket');
insert into Book (id, isbn, title, publisher) values (102, 9781932394825, 'Ibatis in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (103, 9789176437612, 'Det Verkliga Livet', 'ManPocket');
insert into Book (id, isbn, title, publisher) values (104, 9781932394849, 'Groovy in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (105, 9781933988238, 'Gwt in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (106, 9781884777561, 'The Awesome Power of Java Beans', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (107, 9781932394740, 'Hacking with Ruby', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (108, 9781932394771, 'ASP.Net 2.0 Web Parts in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (109, 9781932394795, 'Itext in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (110, 9781932394764, 'SQL Server 2005 Reporting Services in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (111, 9781932394504, 'Minimal Perl', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (112, 9781932394443, 'IntelliJ IDEA in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (113, 9781932394696, 'Ruby for Rails ', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (114, 9781884777813, 'Python and Tkinter Programming', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (115, 9781884777653, 'Distributed Programming with Java', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (116, 9781933988344, 'EJB 3 in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (117, 9781933988030, 'Prototype and Scriptaculous in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (118, 9781932394993, 'Ajax in Practice', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (119, 9781932394818, 'C++/CLI in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (120, 9781932394542, 'Portlets and Apache Portals', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (121, 9781930110984, 'Programming Windows Server 2003', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (122, 9781932394627, 'wxPython in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (123, 9781932394580, 'POJOs in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (124, 9781884777752, 'Up to Speed with Swing', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (125, 9781932394658, 'Windows Forms in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (126, 9781884777677, 'Java Foundation Classes', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (127, 9789984574134, 'Latvijas Republikas civillikuma komentari: Lietas, valdijums, tiesibas uz svesu lietu ', 'Mans Ipasums');
insert into Book (id, isbn, title, publisher) values (128, 9781935182559, 'Continuous Integration in .NET', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (129, 9781935182405, 'ASP.NET Ajax in Action, Second Edition', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (130, 9781935182580, 'iPhone and iPad in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (131, 9789176437988, 'De Galnas Hus', 'ManPocket,');
insert into Book (id, isbn, title, publisher) values (132, 9781935182184, 'Microsoft Entity Framework in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (133, 9781933988610, 'IronRuby in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (134, 9781933988535, 'Hello! Silverlight 3', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (135, 9781935182726, 'Unlocking Android', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (136, 9781935182481, 'Azure in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (137, 9781935182214, 'Event Processing in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (138, 9781933988795, 'Flex on Java', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (139, 9781935182368, 'Camel in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (140, 9781935182450, 'DSLs in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (141, 9781933988894, 'Tuscany SCA in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (142, 9781935182825, 'Liferay in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (143, 9781935182139, 'Windows Powershell in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (144, 9789170011818, 'Morkerspar', 'ManPocket');
insert into Book (id, isbn, title, publisher) values (145, 9781935182306, 'Spring Dynamic Modules in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (146, 9789176434932, 'Rosario �r D�d', 'ManPocket');
insert into Book (id, isbn, title, publisher) values (147, 9789176434185, 'Angeln pa sjunde trapp-steget', 'ManPocket');
insert into Book (id, isbn, title, publisher) values (148, 9789170010415, 'POJKEN SOM INTE FANNS.', 'ManPocket');
insert into Book (id, isbn, title, publisher) values (149, 9781935182474, 'C# in Depth, Second Edition', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (150, 9781935182269, 'PostGIS in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (151, 9781935182610, 'iText in Action, Second Edition', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (152, 9781935182542, 'Portlets in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (153, 9781935182641, 'The Joy of Clojure', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (154, 9781935182085, 'Hello! Python', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (155, 9781935182054, 'Spring in Practice', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (156, 9789984574127, 'Latvijas Republikas civillikuma komentari', 'Mans ipasums');
insert into Book (id, isbn, title, publisher) values (157, 9781935182191, 'Hadoop in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (158, 9781935182795, 'ASP.NET MVC 2 in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (159, 9781935182528, 'The Cloud at Your Service', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (160, 9781935182238, 'Griffon in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (161, 9781599592138, '29 CFR 1926 OSHA Construction Industry Regulations', 'ManComm');
insert into Book (id, isbn, title, publisher) values (162, 9781932394344, 'Microsoft reporting services in action', 'Greenwich, CT : Manning Publications, c2005.');
insert into Book (id, isbn, title, publisher) values (163, 9781617290176, 'OpenCL in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (164, 9781935182856, 'Tika in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (165, 9789170011986, 'Jonas Eckel', 'ManPocket');
insert into Book (id, isbn, title, publisher) values (166, 9781935182627, 'Generative Art', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (167, 9781935182337, 'Location-Aware Applications', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (168, 9781617290183, 'Machine Learning in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (169, 9781617290497, 'HTML5 in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (170, 9781617290572, 'Node.js in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (171, 9781617290121, 'Activiti in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (172, 9781617290329, 'Ext JS in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (173, 9789176428603, 'Firman', 'ManPocket');
insert into Book (id, isbn, title, publisher) values (174, 9781935182498, 'MacRuby in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (175, 9789176436165, 'Forsvararen', 'ManPocket');
insert into Book (id, isbn, title, publisher) values (176, 9781617290473, 'SQL Server MVP Deep Dives, Volume 2', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (177, 9781930110038, 'Taming Jaguar', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (178, 9781617290411, 'ASP.NET MVC 3 in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (179, 9781935182672, 'iPhone Art, iPad Art', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (180, 9780935717150, 'Spring in Action 3th (third) edition', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (181, 9789176439609, 'Smartbararen', 'ManPocket');
insert into Book (id, isbn, title, publisher) values (182, 9781935182955, 'Spring Batch in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (183, 9781933988757, 'SharePoint 2010 Site Owner''s Manual', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (184, 9781935182894, 'Quick & Easy HTML5 and CSS3', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (185, 9781935182979, 'RabbitMQ in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (186, 9789176438602, 'POJKEN SOM KALLADES DET.', 'ManPocket');
insert into Book (id, isbn, title, publisher) values (187, 9781935182276, 'Rails 3 in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (188, 9781935182818, 'Natural User Interfaces in .NET', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (189, 9781935182535, 'Objective-C Fundamentals', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (190, 9781935182801, 'Lift in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (191, 9781935182702, 'Scala in Depth', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (192, 9781935182962, 'Spring Roo in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (193, 9789176437179, 'JOHN GRISHAM TESTAMENTET.', 'ManPocket');
insert into Book (id, isbn, title, publisher) values (194, 9781933988146, 'ASP.NET AJAX in Action', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (195, 9780132612319, 'Object technology centers of excellence', 'Greenwich, CT : Manning Publications, c1996.');
insert into Book (id, isbn, title, publisher) values (196, 9781884777660, 'Java Servlets by Example', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (197, 9781933988474, 'Ruby in Practice', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (198, 9781933988658, 'The Well-Grounded Rubyist', 'Manning Publications');
insert into Book (id, isbn, title, publisher) values (199, 9781933988603, 'Building Domain Specific Languages in Boo', 'Manning Publications');
insert into Author (id, name) values (0, 'Reenskaug, Trygve');
insert into Author (id, name) values (1, 'Wold, P.');
insert into Author (id, name) values (2, 'Lehne, O. A.');
insert into Author (id, name) values (3, 'Wold, Per');
insert into Author (id, name) values (4, 'Lehne, Odd Arild');
insert into Author (id, name) values (5, 'EL-Rewini, Hesham');
insert into Author (id, name) values (6, 'Lewis, T. G.');
insert into Author (id, name) values (7, 'Burnett, Margaret');
insert into Author (id, name) values (8, 'Goldberg, Adele');
insert into Author (id, name) values (9, 'Lussier, K.');
insert into Author (id, name) values (10, 'Brock, Dean');
insert into Author (id, name) values (11, 'Benites, Bob');
insert into Author (id, name) values (12, 'Malkin, Gary Scott');
insert into Author (id, name) values (13, 'Steinman, Scott B.');
insert into Author (id, name) values (14, 'Carver, Kevin G.');
insert into Author (id, name) values (15, 'Rosen, Evan');
insert into Author (id, name) values (16, 'Robinson, Matthew');
insert into Author (id, name) values (17, 'Pavel Vorobiev');
insert into Author (id, name) values (18, 'Erik Hatcher');
insert into Author (id, name) values (19, 'Steve Loughran');
insert into Author (id, name) values (20, 'David Gallardo');
insert into Author (id, name) values (21, 'Ed Burnette');
insert into Author (id, name) values (22, 'McGovern, Robert');
insert into Author (id, name) values (23, 'Ernest Friedman-Hill');
insert into Author (id, name) values (24, 'Thomas B. Passin');
insert into Author (id, name) values (25, 'Bruce Payette');
insert into Author (id, name) values (26, 'Christian Bauer');
insert into Author (id, name) values (27, 'Gavin King');
insert into Author (id, name) values (28, 'Birman, Kenneth P.');
insert into Author (id, name) values (29, 'Pierre Kuate');
insert into Author (id, name) values (30, 'Minoli, Daniel');
insert into Author (id, name) values (31, 'Golway, Tom');
insert into Author (id, name) values (32, 'Smith, Norris');
insert into Author (id, name) values (33, 'Gregory M. Travis');
insert into Author (id, name) values (34, 'Travis, Greg M.');
insert into Author (id, name) values (35, 'Early Stephens');
insert into Author (id, name) values (36, 'Grayson, John');
insert into Author (id, name) values (37, 'Jon Perry');
insert into Author (id, name) values (38, 'J. B. Rainsberger');
insert into Author (id, name) values (39, 'Scott Stirling');
insert into Author (id, name) values (40, 'Schmidt, Andrew');
insert into Author (id, name) values (41, 'Manning, Marelyn R.');
insert into Author (id, name) values (42, 'Rodrigues, Lawrence H.');
insert into Author (id, name) values (43, 'Ron Stanley');
insert into Author (id, name) values (44, 'Levi Asher');
insert into Author (id, name) values (45, 'Haralambos Marmanis');
insert into Author (id, name) values (46, 'Dmitry Babenko');
insert into Author (id, name) values (47, 'Tate, Bruce');
insert into Author (id, name) values (48, 'Cockayne, William R.');
insert into Author (id, name) values (49, 'Zyda, Michael');
insert into Author (id, name) values (50, 'Paul S. Hethmon');
insert into Author (id, name) values (51, 'Lynch, Daniel');
insert into Author (id, name) values (52, 'Gray, James');
insert into Author (id, name) values (53, 'Rabinovitch, Edward');
insert into Author (id, name) values (54, 'Bakman, Alex');
insert into Author (id, name) values (55, 'Lasse Koskela');
insert into Author (id, name) values (56, 'Ben G. Sullins');
insert into Author (id, name) values (57, 'Mark B. Whipple');
insert into Author (id, name) values (58, 'Tarak Modi');
insert into Author (id, name) values (59, 'Ted Husted');
insert into Author (id, name) values (60, 'Bancroft, Nancy H.');
insert into Author (id, name) values (61, 'Mike Clark');
insert into Author (id, name) values (62, 'Lee, Bob H.');
insert into Author (id, name) values (63, 'Patrick Linskey');
insert into Author (id, name) values (64, 'Dave Crane');
insert into Author (id, name) values (65, 'Eric Pascarello');
insert into Author (id, name) values (66, 'Bennett, Douglas H.');
insert into Author (id, name) values (67, 'Thomas W. Golway');
insert into Author (id, name) values (68, 'Manning Publications');
insert into Author (id, name) values (69, 'Henning Seip');
insert into Author (id, name) values (70, 'Andrea Sprengel');
insert into Author (id, name) values (71, 'Patrick Peak');
insert into Author (id, name) values (72, 'Nick Heudecker');
insert into Author (id, name) values (73, 'Eric Pulier');
insert into Author (id, name) values (74, 'Taylor, Hugh');
insert into Author (id, name) values (75, 'Tim Jenness');
insert into Author (id, name) values (76, 'Simon Cozens');
insert into Author (id, name) values (77, 'Theo Petersen');
insert into Author (id, name) values (78, 'translated by John Fairbairn Aono Teruichi');
insert into Author (id, name) values (79, 'Caleb MacLennan');
insert into Author (id, name) values (80, 'Delaney, Dylan');
insert into Author (id, name) values (81, 'Case, Cameron');
insert into Author (id, name) values (82, 'Cassidy, Ben');
insert into Author (id, name) values (83, 'Manning, Aidan');
insert into Author (id, name) values (84, 'Pratt, William K.');
insert into Author (id, name) values (85, 'Hughes, M.');
insert into Author (id, name) values (86, 'Sporle, Peter J.');
insert into Author (id, name) values (87, 'Manning, Robert');
insert into Author (id, name) values (88, 'Cedric Dumoulin');
insert into Author (id, name) values (89, 'George Franciscus');
insert into Author (id, name) values (90, 'David Winterfeldt');
insert into Author (id, name) values (91, 'Craig R. McClanahan');
insert into Author (id, name) values (92, 'Vincent Massol');
insert into Author (id, name) values (93, 'Craig Walls');
insert into Author (id, name) values (94, 'Richards, Norman');
insert into Author (id, name) values (95, 'Rickard Oberg');
insert into Author (id, name) values (96, 'Ramnivas Laddad');
insert into Author (id, name) values (97, 'Kito D. Mann');
insert into Author (id, name) values (98, 'Jack Herrington');
insert into Author (id, name) values (99, 'Hanumant Deshmukh');
insert into Author (id, name) values (100, 'Jignesh Malavia');
insert into Author (id, name) values (101, 'Jacquelyn Carter');
insert into Author (id, name) values (102, 'Merlin Hughes');
insert into Author (id, name) values (103, 'Michael Shoffner');
insert into Author (id, name) values (104, 'Derek Hamner');
insert into Author (id, name) values (105, 'Forman, Ira N.');
insert into Author (id, name) values (106, 'Nate Forman');
insert into Author (id, name) values (107, 'PhD., Ira R. Forman');
insert into Author (id, name) values (108, 'Benjamin L. Kovitz');
insert into Author (id, name) values (109, 'Teo Lachev');
insert into Author (id, name) values (110, 'Harms, Daryl D.');
insert into Author (id, name) values (111, 'McDonald, Kenneth');
insert into Author (id, name) values (112, 'Johnson, Andrew');
insert into Author (id, name) values (113, 'Keyes, Marian');
insert into Author (id, name) values (114, 'Clinton Begin');
insert into Author (id, name) values (115, 'Brandon Goodin');
insert into Author (id, name) values (116, 'Larry Meadors');
insert into Author (id, name) values (117, 'Holst, Hanne-Vibeke');
insert into Author (id, name) values (118, 'Dierk Koenig');
insert into Author (id, name) values (119, 'Guillaume Laforge');
insert into Author (id, name) values (120, 'Andrew Glover');
insert into Author (id, name) values (121, 'Gosling, James');
insert into Author (id, name) values (122, 'Hanson, Robert W.');
insert into Author (id, name) values (123, 'Adam Tacy');
insert into Author (id, name) values (124, 'Watson, Mark');
insert into Author (id, name) values (125, 'Darren Neimke');
insert into Author (id, name) values (126, 'Bruno Lowagie');
insert into Author (id, name) values (127, 'Bret Updegraff');
insert into Author (id, name) values (128, 'Tim Maher');
insert into Author (id, name) values (129, 'Duane K. Fields');
insert into Author (id, name) values (130, 'Saunders, Stephen');
insert into Author (id, name) values (131, 'Eugene Belayev');
insert into Author (id, name) values (132, 'Black, David St Clair');
insert into Author (id, name) values (133, 'Mahmoud, Qusay H.');
insert into Author (id, name) values (134, 'Debu Panda');
insert into Author (id, name) values (135, 'Reza Rahman');
insert into Author (id, name) values (136, 'Derek Lane');
insert into Author (id, name) values (137, 'Bear Bibeault');
insert into Author (id, name) values (138, 'Tom Locke');
insert into Author (id, name) values (139, 'Fuchs, Thomas');
insert into Author (id, name) values (140, 'Jord Sonneveld');
insert into Author (id, name) values (141, 'Ted Goddard');
insert into Author (id, name) values (142, 'Gray, Chris Hables');
insert into Author (id, name) values (143, 'Ram Venkataraman');
insert into Author (id, name) values (144, 'Walker, Joe');
insert into Author (id, name) values (145, 'Sivakumar, Nishant');
insert into Author (id, name) values (146, 'Stefan Hepper');
insert into Author (id, name) values (147, 'Fischer, Peter');
insert into Author (id, name) values (148, 'Stephan Hesmer');
insert into Author (id, name) values (149, 'Richard Jacob');
insert into Author (id, name) values (150, 'Taylor, David H.');
insert into Author (id, name) values (151, 'Foster, Robert John');
insert into Author (id, name) values (152, 'Rappin, Noel');
insert into Author (id, name) values (153, 'Robin MacRae Dunn');
insert into Author (id, name) values (154, 'Richardson, Chris');
insert into Author (id, name) values (155, 'Steven J. Gutz');
insert into Author (id, name) values (156, 'Brown, Erik');
insert into Author (id, name) values (157, 'Stephen C. Drye');
insert into Author (id, name) values (158, 'Wake, William Charles');
insert into Author (id, name) values (159, 'G Visnakova');
insert into Author (id, name) values (160, 'Marcin Kawalerowicz');
insert into Author (id, name) values (161, 'Craig Berntson');
insert into Author (id, name) values (162, 'Alessandro Gallo');
insert into Author (id, name) values (163, 'David Barkol');
insert into Author (id, name) values (164, 'Rama Vavilala');
insert into Author (id, name) values (165, 'Ward, Dave');
insert into Author (id, name) values (166, 'Brandon Trebitowski');
insert into Author (id, name) values (167, 'Allen, Christopher');
insert into Author (id, name) values (168, 'Shannon Appelcline');
insert into Author (id, name) values (169, 'Karin Fossun');
insert into Author (id, name) values (170, 'Stefano Mostarda');
insert into Author (id, name) values (171, 'Marcos De Sanctis');
insert into Author (id, name) values (172, 'Ivan Porto Carrero');
insert into Author (id, name) values (173, 'Adam Burmister');
insert into Author (id, name) values (174, 'Reiss, Bill');
insert into Author (id, name) values (175, 'Campbell, Dave A.');
insert into Author (id, name) values (176, 'Frank Ableson');
insert into Author (id, name) values (177, 'Sen, Robi');
insert into Author (id, name) values (178, 'Chris Hay');
insert into Author (id, name) values (179, 'Brian Prince');
insert into Author (id, name) values (180, 'Etzion, Opher');
insert into Author (id, name) values (181, 'Peter Niblett');
insert into Author (id, name) values (182, 'BJ Allmon');
insert into Author (id, name) values (183, 'Jeremy Anderson');
insert into Author (id, name) values (184, 'Claus Ibsen');
insert into Author (id, name) values (185, 'Jonathan Anstey');
insert into Author (id, name) values (186, 'Debasish Ghosh');
insert into Author (id, name) values (187, 'Simon Laws');
insert into Author (id, name) values (188, 'Mark Combellack');
insert into Author (id, name) values (189, 'Raymond Feng');
insert into Author (id, name) values (190, 'Haleh Mahbod');
insert into Author (id, name) values (191, 'Simon Nash');
insert into Author (id, name) values (192, 'Rich Sezov');
insert into Author (id, name) values (193, 'Inger Frimansson');
insert into Author (id, name) values (194, 'Arnaud Cogoluegnes');
insert into Author (id, name) values (195, 'Thierry Templier');
insert into Author (id, name) values (196, 'Andy Piper');
insert into Author (id, name) values (197, 'Dave Pelzer');
insert into Author (id, name) values (198, 'Jon Skeet');
insert into Author (id, name) values (199, 'Regina Obe');
insert into Author (id, name) values (200, 'Leo Hsu');
insert into Author (id, name) values (201, 'Ashish Sarin');
insert into Author (id, name) values (202, 'Michael Fogus');
insert into Author (id, name) values (203, 'Chris Houser');
insert into Author (id, name) values (204, 'Anthony Briggs');
insert into Author (id, name) values (205, 'Willie Wheeler');
insert into Author (id, name) values (206, 'John Wheeler LLM');
insert into Author (id, name) values (207, 'Wheeler Willie');
insert into Author (id, name) values (208, 'John, Wheeler');
insert into Author (id, name) values (209, 'Chuck Lam');
insert into Author (id, name) values (210, 'Jeffrey Palermo');
insert into Author (id, name) values (211, 'Ben Scheirman');
insert into Author (id, name) values (212, 'Jimmy Bogard');
insert into Author (id, name) values (213, 'Eric Hexter');
insert into Author (id, name) values (214, 'Matthew Hinze');
insert into Author (id, name) values (215, 'Jothy Rosenberg');
insert into Author (id, name) values (216, 'Arthur Mateos');
insert into Author (id, name) values (217, 'Andres Almiray');
insert into Author (id, name) values (218, 'Danno Ferrin');
insert into Author (id, name) values (219, 'Mangan Communications');
insert into Author (id, name) values (220, 'Matthew Scarpino');
insert into Author (id, name) values (221, 'Chris Mattmann');
insert into Author (id, name) values (222, 'Jukka Zitting');
insert into Author (id, name) values (223, 'Fossum, Karin');
insert into Author (id, name) values (224, 'Matt Pearson');
insert into Author (id, name) values (225, 'Ferraro, Richard F.');
insert into Author (id, name) values (226, 'Murat Aktihanoglu');
insert into Author (id, name) values (227, 'Peter Harrington');
insert into Author (id, name) values (228, 'Rob Crowther');
insert into Author (id, name) values (229, 'Joe Lennon');
insert into Author (id, name) values (230, 'Ash Blue');
insert into Author (id, name) values (231, 'Mike Cantelon');
insert into Author (id, name) values (232, 'TJ Holowaychuk');
insert into Author (id, name) values (233, 'Tijs Rademakers');
insert into Author (id, name) values (234, 'Garcia, Jesus');
insert into Author (id, name) values (235, 'Jacob Andresen');
insert into Author (id, name) values (236, 'Grgur Grisogono');
insert into Author (id, name) values (237, 'Grisham, John');
insert into Author (id, name) values (238, 'Brendan G. Lim');
insert into Author (id, name) values (239, 'Jerry Cheung');
insert into Author (id, name) values (240, 'Jeremy McAnally');
insert into Author (id, name) values (241, 'Delaney, Kalen');
insert into Author (id, name) values (242, 'Louis Davidson');
insert into Author (id, name) values (243, 'Greg Low');
insert into Author (id, name) values (244, 'Brad McGhee');
insert into Author (id, name) values (245, 'Nielson, Paul Anthon');
insert into Author (id, name) values (246, 'Paul S. Randal');
insert into Author (id, name) values (247, 'Kimberly L. Tripp');
insert into Author (id, name) values (248, 'Weiss, Jason');
insert into Author (id, name) values (249, 'Michael Barlotta');
insert into Author (id, name) values (250, 'Skinner, Jeremy');
insert into Author (id, name) values (251, 'Asa Nilsonne');
insert into Author (id, name) values (252, 'Gary Gregory');
insert into Author (id, name) values (253, 'Olivier Bazoud');
insert into Author (id, name) values (254, 'Yvonne M. Harryman');
insert into Author (id, name) values (255, 'Alvaro Videla');
insert into Author (id, name) values (256, 'Jason Williams');
insert into Author (id, name) values (257, 'Yehuda Katz');
insert into Author (id, name) values (258, 'Ryan Bigg');
insert into Author (id, name) values (259, 'Joshua Blake');
insert into Author (id, name) values (260, 'Christopher Fairbairn');
insert into Author (id, name) values (261, 'Collin Ruffenach');
insert into Author (id, name) values (262, 'Johannes Fahrenkrug');
insert into Author (id, name) values (263, 'Timothy Perrett');
insert into Author (id, name) values (264, 'Ken Rimple');
insert into Author (id, name) values (265, 'Srini Penchikala');
insert into Author (id, name) values (266, 'Gordon Dickens');
insert into Author (id, name) values (267, 'Lundwall, Sam J.');
insert into Author (id, name) values (268, 'Scott Guthrie');
insert into Author (id, name) values (269, 'Bertrand Le Roy');
insert into Author (id, name) values (270, 'Tim Korson');
insert into Author (id, name) values (271, 'Vijay Vaishnavi');
insert into Author (id, name) values (272, 'Williamson, Alan');
insert into Author (id, name) values (273, 'Assaf Arkin');
insert into Author (id, name) values (274, 'Ayende Rahien');
insert into Book_Author (Book_id, authors_id) values (1, 4);
insert into Book_Author (Book_id, authors_id) values (2, 6);
insert into Book_Author (Book_id, authors_id) values (3, 6);
insert into Book_Author (Book_id, authors_id) values (4, 6);
insert into Book_Author (Book_id, authors_id) values (5, 9);
insert into Book_Author (Book_id, authors_id) values (6, 11);
insert into Book_Author (Book_id, authors_id) values (7, 11);
insert into Book_Author (Book_id, authors_id) values (8, 12);
insert into Book_Author (Book_id, authors_id) values (9, 12);
insert into Book_Author (Book_id, authors_id) values (10, 14);
insert into Book_Author (Book_id, authors_id) values (11, 14);
insert into Book_Author (Book_id, authors_id) values (12, 15);
insert into Book_Author (Book_id, authors_id) values (13, 17);
insert into Book_Author (Book_id, authors_id) values (14, 19);
insert into Book_Author (Book_id, authors_id) values (15, 22);
insert into Book_Author (Book_id, authors_id) values (16, 23);
insert into Book_Author (Book_id, authors_id) values (17, 24);
insert into Book_Author (Book_id, authors_id) values (18, 25);
insert into Book_Author (Book_id, authors_id) values (19, 27);
insert into Book_Author (Book_id, authors_id) values (20, 15);
insert into Book_Author (Book_id, authors_id) values (21, 28);
insert into Book_Author (Book_id, authors_id) values (22, 28);
insert into Book_Author (Book_id, authors_id) values (23, 27);
insert into Book_Author (Book_id, authors_id) values (24, 32);
insert into Book_Author (Book_id, authors_id) values (25, 34);
insert into Book_Author (Book_id, authors_id) values (26, 35);
insert into Book_Author (Book_id, authors_id) values (27, 37);
insert into Book_Author (Book_id, authors_id) values (28, 22);
insert into Book_Author (Book_id, authors_id) values (30, 39);
insert into Book_Author (Book_id, authors_id) values (31, 40);
insert into Book_Author (Book_id, authors_id) values (32, 40);
insert into Book_Author (Book_id, authors_id) values (33, 41);
insert into Book_Author (Book_id, authors_id) values (34, 42);
insert into Book_Author (Book_id, authors_id) values (36, 35);
insert into Book_Author (Book_id, authors_id) values (37, 43);
insert into Book_Author (Book_id, authors_id) values (39, 44);
insert into Book_Author (Book_id, authors_id) values (40, 46);
insert into Book_Author (Book_id, authors_id) values (41, 47);
insert into Book_Author (Book_id, authors_id) values (42, 17);
insert into Book_Author (Book_id, authors_id) values (43, 21);
insert into Book_Author (Book_id, authors_id) values (44, 49);
insert into Book_Author (Book_id, authors_id) values (45, 49);
insert into Book_Author (Book_id, authors_id) values (46, 50);
insert into Book_Author (Book_id, authors_id) values (47, 53);
insert into Book_Author (Book_id, authors_id) values (48, 50);
insert into Book_Author (Book_id, authors_id) values (49, 54);
insert into Book_Author (Book_id, authors_id) values (50, 54);
insert into Book_Author (Book_id, authors_id) values (51, 55);
insert into Book_Author (Book_id, authors_id) values (52, 57);
insert into Book_Author (Book_id, authors_id) values (53, 4);
insert into Book_Author (Book_id, authors_id) values (54, 58);
insert into Book_Author (Book_id, authors_id) values (55, 30);
insert into Book_Author (Book_id, authors_id) values (56, 30);
insert into Book_Author (Book_id, authors_id) values (57, 59);
insert into Book_Author (Book_id, authors_id) values (58, 19);
insert into Book_Author (Book_id, authors_id) values (59, 60);
insert into Book_Author (Book_id, authors_id) values (60, 60);
insert into Book_Author (Book_id, authors_id) values (61, 63);
insert into Book_Author (Book_id, authors_id) values (62, 65);
insert into Book_Author (Book_id, authors_id) values (63, 66);
insert into Book_Author (Book_id, authors_id) values (64, 66);
insert into Book_Author (Book_id, authors_id) values (65, 31);
insert into Book_Author (Book_id, authors_id) values (66, 70);
insert into Book_Author (Book_id, authors_id) values (67, 72);
insert into Book_Author (Book_id, authors_id) values (68, 74);
insert into Book_Author (Book_id, authors_id) values (69, 76);
insert into Book_Author (Book_id, authors_id) values (70, 77);
insert into Book_Author (Book_id, authors_id) values (71, 22);
insert into Book_Author (Book_id, authors_id) values (72, 41);
insert into Book_Author (Book_id, authors_id) values (73, 78);
insert into Book_Author (Book_id, authors_id) values (74, 79);
insert into Book_Author (Book_id, authors_id) values (76, 80);
insert into Book_Author (Book_id, authors_id) values (77, 81);
insert into Book_Author (Book_id, authors_id) values (78, 82);
insert into Book_Author (Book_id, authors_id) values (79, 83);
insert into Book_Author (Book_id, authors_id) values (80, 84);
insert into Book_Author (Book_id, authors_id) values (81, 84);
insert into Book_Author (Book_id, authors_id) values (82, 85);
insert into Book_Author (Book_id, authors_id) values (83, 85);
insert into Book_Author (Book_id, authors_id) values (84, 86);
insert into Book_Author (Book_id, authors_id) values (85, 87);
insert into Book_Author (Book_id, authors_id) values (86, 91);
insert into Book_Author (Book_id, authors_id) values (87, 59);
insert into Book_Author (Book_id, authors_id) values (88, 95);
insert into Book_Author (Book_id, authors_id) values (89, 27);
insert into Book_Author (Book_id, authors_id) values (90, 39);
insert into Book_Author (Book_id, authors_id) values (91, 96);
insert into Book_Author (Book_id, authors_id) values (92, 97);
insert into Book_Author (Book_id, authors_id) values (93, 98);
insert into Book_Author (Book_id, authors_id) values (94, 101);
insert into Book_Author (Book_id, authors_id) values (95, 104);
insert into Book_Author (Book_id, authors_id) values (96, 107);
insert into Book_Author (Book_id, authors_id) values (98, 108);
insert into Book_Author (Book_id, authors_id) values (99, 109);
insert into Book_Author (Book_id, authors_id) values (100, 111);
insert into Book_Author (Book_id, authors_id) values (101, 112);
insert into Book_Author (Book_id, authors_id) values (102, 113);
insert into Book_Author (Book_id, authors_id) values (103, 116);
insert into Book_Author (Book_id, authors_id) values (104, 117);
insert into Book_Author (Book_id, authors_id) values (105, 121);
insert into Book_Author (Book_id, authors_id) values (106, 123);
insert into Book_Author (Book_id, authors_id) values (107, 42);
insert into Book_Author (Book_id, authors_id) values (108, 124);
insert into Book_Author (Book_id, authors_id) values (109, 125);
insert into Book_Author (Book_id, authors_id) values (110, 126);
insert into Book_Author (Book_id, authors_id) values (111, 127);
insert into Book_Author (Book_id, authors_id) values (112, 128);
insert into Book_Author (Book_id, authors_id) values (113, 131);
insert into Book_Author (Book_id, authors_id) values (114, 132);
insert into Book_Author (Book_id, authors_id) values (115, 36);
insert into Book_Author (Book_id, authors_id) values (116, 133);
insert into Book_Author (Book_id, authors_id) values (117, 136);
insert into Book_Author (Book_id, authors_id) values (118, 139);
insert into Book_Author (Book_id, authors_id) values (119, 144);
insert into Book_Author (Book_id, authors_id) values (120, 145);
insert into Book_Author (Book_id, authors_id) values (121, 150);
insert into Book_Author (Book_id, authors_id) values (122, 151);
insert into Book_Author (Book_id, authors_id) values (123, 153);
insert into Book_Author (Book_id, authors_id) values (124, 154);
insert into Book_Author (Book_id, authors_id) values (125, 17);
insert into Book_Author (Book_id, authors_id) values (126, 156);
insert into Book_Author (Book_id, authors_id) values (127, 158);
insert into Book_Author (Book_id, authors_id) values (128, 159);
insert into Book_Author (Book_id, authors_id) values (129, 161);
insert into Book_Author (Book_id, authors_id) values (130, 165);
insert into Book_Author (Book_id, authors_id) values (131, 168);
insert into Book_Author (Book_id, authors_id) values (132, 169);
insert into Book_Author (Book_id, authors_id) values (133, 171);
insert into Book_Author (Book_id, authors_id) values (134, 173);
insert into Book_Author (Book_id, authors_id) values (135, 175);
insert into Book_Author (Book_id, authors_id) values (136, 177);
insert into Book_Author (Book_id, authors_id) values (137, 179);
insert into Book_Author (Book_id, authors_id) values (138, 181);
insert into Book_Author (Book_id, authors_id) values (139, 183);
insert into Book_Author (Book_id, authors_id) values (140, 185);
insert into Book_Author (Book_id, authors_id) values (141, 186);
insert into Book_Author (Book_id, authors_id) values (142, 191);
insert into Book_Author (Book_id, authors_id) values (143, 192);
insert into Book_Author (Book_id, authors_id) values (144, 25);
insert into Book_Author (Book_id, authors_id) values (145, 193);
insert into Book_Author (Book_id, authors_id) values (146, 196);
insert into Book_Author (Book_id, authors_id) values (149, 197);
insert into Book_Author (Book_id, authors_id) values (150, 198);
insert into Book_Author (Book_id, authors_id) values (151, 200);
insert into Book_Author (Book_id, authors_id) values (152, 126);
insert into Book_Author (Book_id, authors_id) values (153, 201);
insert into Book_Author (Book_id, authors_id) values (154, 203);
insert into Book_Author (Book_id, authors_id) values (155, 204);
insert into Book_Author (Book_id, authors_id) values (156, 208);
insert into Book_Author (Book_id, authors_id) values (158, 209);
insert into Book_Author (Book_id, authors_id) values (159, 214);
insert into Book_Author (Book_id, authors_id) values (160, 216);
insert into Book_Author (Book_id, authors_id) values (161, 218);
insert into Book_Author (Book_id, authors_id) values (162, 219);
insert into Book_Author (Book_id, authors_id) values (163, 109);
insert into Book_Author (Book_id, authors_id) values (164, 220);
insert into Book_Author (Book_id, authors_id) values (165, 222);
insert into Book_Author (Book_id, authors_id) values (166, 223);
insert into Book_Author (Book_id, authors_id) values (167, 224);
insert into Book_Author (Book_id, authors_id) values (168, 226);
insert into Book_Author (Book_id, authors_id) values (169, 227);
insert into Book_Author (Book_id, authors_id) values (170, 230);
insert into Book_Author (Book_id, authors_id) values (171, 232);
insert into Book_Author (Book_id, authors_id) values (172, 233);
insert into Book_Author (Book_id, authors_id) values (173, 236);
insert into Book_Author (Book_id, authors_id) values (174, 237);
insert into Book_Author (Book_id, authors_id) values (175, 240);
insert into Book_Author (Book_id, authors_id) values (176, 237);
insert into Book_Author (Book_id, authors_id) values (177, 247);
insert into Book_Author (Book_id, authors_id) values (178, 249);
insert into Book_Author (Book_id, authors_id) values (179, 250);
insert into Book_Author (Book_id, authors_id) values (181, 93);
insert into Book_Author (Book_id, authors_id) values (182, 251);
insert into Book_Author (Book_id, authors_id) values (183, 253);
insert into Book_Author (Book_id, authors_id) values (184, 254);
insert into Book_Author (Book_id, authors_id) values (185, 228);
insert into Book_Author (Book_id, authors_id) values (186, 256);
insert into Book_Author (Book_id, authors_id) values (187, 197);
insert into Book_Author (Book_id, authors_id) values (188, 258);
insert into Book_Author (Book_id, authors_id) values (189, 259);
insert into Book_Author (Book_id, authors_id) values (190, 262);
insert into Book_Author (Book_id, authors_id) values (191, 263);
insert into Book_Author (Book_id, authors_id) values (193, 266);
insert into Book_Author (Book_id, authors_id) values (194, 267);
insert into Book_Author (Book_id, authors_id) values (195, 269);
insert into Book_Author (Book_id, authors_id) values (196, 271);
insert into Book_Author (Book_id, authors_id) values (197, 272);
insert into Book_Author (Book_id, authors_id) values (198, 273);
insert into Book_Author (Book_id, authors_id) values (199, 132);
